language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

branches:
  only:
    - master

bundler_args: --jobs 7

before_script:
  - git config --global user.email "ci@traivs-ci.org"
  - git config --global user.name "Travis CI"

script: bundle exec rake
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.4.0